version: '3'

services:
#  neo4j:
#    image: neo4j:latest
#    network_mode: "bridge"
#    ports:
#      - "7474:7474"
#      - "7473:7473"
#      - "7687:7687"
#    environment:
#      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
#      - NEO4J_AUTH=neo4j/test
#    volumes:
#      - ./data/neo4j/plugins:/plugins
#      - ./data/neo4j/data:/data
#      - ./data/neo4j/import:/var/lib/neo4j/import
#      - ./data/neo4j/logs:/logs
  mongo:
    # https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3
    image: mongo:latest
    ports:
    - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dyploma
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro