version: '3'

services:
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_AUTH=neo4j/test
    volumes:
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/data:/data
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/logs:/logs